apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio-server 
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args: 
      - server
      - /data
      - --console-address 
      - :9001
    ports:
      - containerPort: 9000
      - containerPort: 9001
    env:
      - name: MINIO_ROOT_USER
        value: "minioadmin"
      - name: MINIO_ROOT_PASSWORD
        value: "minioadmin"
    volumeMounts:
      - name: minio-data
        mountPath: /data
  volumes:
    - name: minio-data
      emptyDir: {}  

---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: minio 
spec:
  selector:
    app: minio-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: minio
spec:
  selector:
    app: minio-server
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001  