apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: nyc-taxi-trip-started
  namespace: ingestion
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: nyc-taxi-trip-completed
  namespace: ingestion
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
