import os

SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:superset@postgres-superset:5432/superset"
SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY", "nyc-taxi-dev-secret-2024")
SUPERSET_LOAD_EXAMPLES = False
WTF_CSRF_ENABLED = False
TALISMAN_ENABLED = False

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
}

CACHE_CONFIG = {"CACHE_TYPE": "SimpleCache", "CACHE_DEFAULT_TIMEOUT": 300}
ROW_LIMIT = 100000
SQLLAB_TIMEOUT = 300
SUPERSET_WEBSERVER_TIMEOUT = 300
