apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nyc-taxi-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /teamspace/studios/this_studio/NYC_Taxis_BigData_Pipeline/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nyc-taxi-pvc
  namespace: lakehouse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: nfs-nyc-taxi-pv
