apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse
  labels:
    name: lakehouse
    env: development

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingestion
  labels:
    name: ingestion
    env: development

apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: lakehouse
    env: development
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    name: mlops
    env: development 

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    env: development    

---
apiVersion: v1
kind: Namespace
metadata:
  name: serving
  labels:
    name: serving
    env: development
