# -*- coding: utf-8 -*-
"""notebooka2ec3544c7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/nguynhongvit2005/notebooka2ec3544c7.822215ed-01b4-416f-89ec-18b247110243.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260507/auto/storage/goog4_request%26X-Goog-Date%3D20260507T045607Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D2c6c974c6152054c8ac83a5a95f7bd0c9a4452c5522acf2ef437c91b3b79bb05f33d0552057447e2ff7c538dad2813868539b0d3cacf59120ab234825ff341482aee7591bc1cf82ceeca16206befd1a4f6874737757534eb5dfd0cda6a604689637eef1621c1a3e1fa6fcc2085d58c9a2d9bcbd5150dea0ce4469853ba1848b86c57433dd7960bb09b0f454be8a0bee609a194d5cc9ffa34548e2680f3968f8879ac8109d74249acaa970c3aa92204146ed58b98d8523b61fbfb8113e1e53d6f211dccda3aaebea0b685c3c563f830f9173cf8c24cc9f9cf593f0e79e1cc5c74553c91d6904ebe4f335eb08c32b87b57e05b6e8046fdc78aca7bcdce706f944b
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
elemento_nyc_yellow_taxi_trip_data_path = kagglehub.dataset_download('elemento/nyc-yellow-taxi-trip-data')

print('Data source import complete.')

"""# NYC Yellow Taxi Trip Data - March 2016
Complete Data Engineering & ML Pipeline
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import time
import math

from scipy import signal, fft
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import xgboost as xgb

# %matplotlib inline
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

pip install mlflow --quiet

"""# 8. MLflow Setup
Khởi tạo MLflow để track experiments, log metrics và lưu model.
"""

import mlflow
import mlflow.sklearn
import mlflow.xgboost
from mlflow.models.signature import infer_signature

# Khởi tạo MLflow experiment
mlflow.set_experiment("NYC_Taxi_Fare_Prediction")

print(f"MLflow version: {mlflow.__version__}")
print(f"Tracking URI: {mlflow.get_tracking_uri()}")
print("MLflow đã sẵn sàng! Experiment: NYC_Taxi_Fare_Prediction")

"""# 1. Load Raw Data"""

# Tối ưu hóa cho 2GB data
# Cách 1: Đọc chỉ các cột cần thiết và tối ưu data types
dtype_dict = {
    'tpep_pickup_datetime': 'str',
    'tpep_dropoff_datetime': 'str',
    'pickup_latitude': 'float32',
    'pickup_longitude': 'float32',
    'dropoff_latitude': 'float32',
    'dropoff_longitude': 'float32',
    'trip_distance': 'float32',
    'fare_amount': 'float32',
    'passenger_count': 'int8',
    'payment_type': 'int8',
    'extra': 'float32',
    'mta_tax': 'float32',
    'tip_amount': 'float32',
    'tolls_amount': 'float32',
    'total_amount': 'float32'
}

# Chỉ đọc các cột cần thiết
usecols = list(dtype_dict.keys())

df_raw = pd.read_csv(
    '/kaggle/input/datasets/elemento/nyc-yellow-taxi-trip-data/yellow_tripdata_2016-03.csv',
    dtype=dtype_dict,
    usecols=usecols,
    low_memory=False,  # Tránh chạy detection type nhều lần
    engine='c'  # Dùng c engine (nhanh hơn python engine)
)

print(f'Raw Dataset shape: {df_raw.shape}')
print(f'Memory usage: {df_raw.memory_usage(deep=True).sum() / 1024**2:.2f} MB')
print(f'\nFirst few rows:')
print(df_raw.head())
print(f'\nColumns: {df_raw.columns.tolist()}')
print(f'\nMissing values:')
print(df_raw.isnull().sum())
print(f'\nData types:')
print(df_raw.dtypes)

"""# 2. Data Engineering
Extract features from raw data before cleaning
"""

df = df_raw.copy()

# Convert datetime columns
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Extract temporal features
df['pickup_hour'] = df['tpep_pickup_datetime'].dt.hour
df['pickup_day'] = df['tpep_pickup_datetime'].dt.day
df['pickup_day_of_week'] = df['tpep_pickup_datetime'].dt.dayofweek  # 0=Monday, 6=Sunday
df['pickup_month'] = df['tpep_pickup_datetime'].dt.month
df['pickup_minute'] = df['tpep_pickup_datetime'].dt.minute
df['is_weekend'] = df['pickup_day_of_week'].isin([5, 6]).astype(int)

# Extract temporal patterns (sine/cosine for cyclical features)
df['hour_sin'] = np.sin(2 * np.pi * df['pickup_hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['pickup_hour'] / 24)
df['day_sin'] = np.sin(2 * np.pi * df['pickup_day_of_week'] / 7)
df['day_cos'] = np.cos(2 * np.pi * df['pickup_day_of_week'] / 7)

# Calculate trip duration
df['trip_duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60

# Calculate distance components
df['distance_lat'] = df['dropoff_latitude'] - df['pickup_latitude']
df['distance_lon'] = df['dropoff_longitude'] - df['pickup_longitude']
df['distance_manhattan'] = np.abs(df['distance_lat']) + np.abs(df['distance_lon'])

# Speed calculation
df['speed'] = np.where(df['trip_duration'] > 0,
                       (df['trip_distance'] / df['trip_duration']) * 60,
                       0)

# Pickup location zones
df['pickup_lat_zone'] = pd.cut(df['pickup_latitude'], bins=5, labels=False)
df['pickup_lon_zone'] = pd.cut(df['pickup_longitude'], bins=5, labels=False)

print(f'Data after Engineering:')
print(f'Shape: {df.shape}')
print(f'\nEngineer features created:')
print(f'  - Temporal: hour, day, day_of_week, month, minute, is_weekend')
print(f'  - Cyclical: hour_sin, hour_cos, day_sin, day_cos')
print(f'  - Distance: distance_lat, distance_lon, distance_manhattan')
print(f'  - Speed: speed')
print(f'  - Location zones: pickup_lat_zone, pickup_lon_zone')
print(f'\nNew columns sample:')
print(df[['pickup_hour', 'pickup_day_of_week', 'is_weekend', 'hour_sin', 'distance_manhattan', 'speed']].head())

"""# 3. Data Cleaning
Remove outliers and invalid values based on domain knowledge
"""

def clean_data(df):
    df = df.copy()
    initial_rows = len(df)

    # Remove missing values in critical columns
    df = df.dropna(subset=['tpep_pickup_datetime', 'trip_distance', 'fare_amount'])
    print(f'After dropping nulls: {len(df)} rows')

    # Remove invalid trip distances and fares
    df = df[(df['trip_distance'] > 0) & (df['fare_amount'] > 0)]
    print(f'After removing zero distance/fare: {len(df)} rows')

    # NYC geographic bounds
    nyc_min_lat, nyc_max_lat = 40.5774, 40.9176
    nyc_min_lon, nyc_max_lon = -74.15, -73.7004

    df = df[(df['pickup_latitude'] >= nyc_min_lat) & (df['pickup_latitude'] <= nyc_max_lat) &
            (df['pickup_longitude'] >= nyc_min_lon) & (df['pickup_longitude'] <= nyc_max_lon) &
            (df['dropoff_latitude'] >= nyc_min_lat) & (df['dropoff_latitude'] <= nyc_max_lat) &
            (df['dropoff_longitude'] >= nyc_min_lon) & (df['dropoff_longitude'] <= nyc_max_lon)]
    print(f'After NYC bounds filter: {len(df)} rows')

    # Trip duration: 1 min - 12 hours
    df = df[(df['trip_duration'] > 1) & (df['trip_duration'] < 720)]
    print(f'After trip duration filter: {len(df)} rows')

    # Speed: 0 - 45 mph
    df = df[(df['speed'] >= 0) & (df['speed'] < 45)]
    print(f'After speed filter: {len(df)} rows')

    # Passenger count
    df = df[(df['passenger_count'] > 0) & (df['passenger_count'] <= 6)]
    print(f'After passenger count filter: {len(df)} rows')

    pct_removed = 100 * (initial_rows - len(df)) / initial_rows
    print(f'\nTotal removed: {initial_rows - len(df)} rows ({pct_removed:.2f}%)')

    return df

df_clean = clean_data(df)
print(f'\nCleaned dataset shape: {df_clean.shape}')

"""# 4. Smoothing & Time Series Analysis"""

# Sort by pickup datetime for time series analysis
df_ts = df_clean.sort_values('tpep_pickup_datetime').reset_index(drop=True)

# Aggregate by hour for time series
df_hourly = df_ts.groupby(df_ts['tpep_pickup_datetime'].dt.floor('H')).agg({
    'fare_amount': ['mean', 'count', 'std'],
    'trip_distance': 'mean',
    'trip_duration': 'mean',
    'passenger_count': 'mean',
    'speed': 'mean'
}).reset_index()

df_hourly.columns = ['hour', 'avg_fare', 'trip_count', 'fare_std', 'avg_distance',
                      'avg_duration', 'avg_passenger', 'avg_speed']

# Apply moving average smoothing
from scipy.ndimage import uniform_filter1d

window_size = 6  # 6-hour window
df_hourly['avg_fare_smooth'] = uniform_filter1d(df_hourly['avg_fare'], size=window_size, mode='nearest')
df_hourly['trip_count_smooth'] = uniform_filter1d(df_hourly['trip_count'], size=window_size, mode='nearest')

# Exponential weighted moving average
df_hourly['avg_fare_ewma'] = df_hourly['avg_fare'].ewm(span=12).mean()
df_hourly['trip_count_ewma'] = df_hourly['trip_count'].ewm(span=12).mean()

print(f'Hourly aggregated data shape: {df_hourly.shape}')
print(f'\nHourly statistics:')
print(df_hourly[['avg_fare', 'trip_count', 'avg_distance', 'avg_duration']].describe())

# Plot time series with smoothing
fig, axes = plt.subplots(2, 2, figsize=(14, 8))

axes[0, 0].plot(range(len(df_hourly)), df_hourly['avg_fare'], label='Raw', alpha=0.5, linewidth=0.8)
axes[0, 0].plot(range(len(df_hourly)), df_hourly['avg_fare_smooth'], label='Moving Avg', linewidth=2)
axes[0, 0].plot(range(len(df_hourly)), df_hourly['avg_fare_ewma'], label='EWMA', linewidth=2)
axes[0, 0].set_xlabel('Time (hours)')
axes[0, 0].set_ylabel('Avg Fare ($)')
axes[0, 0].set_title('Fare Price Time Series with Smoothing')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].plot(range(len(df_hourly)), df_hourly['trip_count'], label='Raw', alpha=0.5, linewidth=0.8)
axes[0, 1].plot(range(len(df_hourly)), df_hourly['trip_count_smooth'], label='Moving Avg', linewidth=2)
axes[0, 1].plot(range(len(df_hourly)), df_hourly['trip_count_ewma'], label='EWMA', linewidth=2)
axes[0, 1].set_xlabel('Time (hours)')
axes[0, 1].set_ylabel('Trip Count')
axes[0, 1].set_title('Trip Count Time Series with Smoothing')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

axes[1, 0].plot(range(len(df_hourly)), df_hourly['avg_distance'])
axes[1, 0].set_xlabel('Time (hours)')
axes[1, 0].set_ylabel('Avg Distance (miles)')
axes[1, 0].set_title('Average Trip Distance Over Time')
axes[1, 0].grid(True, alpha=0.3)

axes[1, 1].plot(range(len(df_hourly)), df_hourly['avg_speed'])
axes[1, 1].set_xlabel('Time (hours)')
axes[1, 1].set_ylabel('Avg Speed (mph)')
axes[1, 1].set_title('Average Speed Over Time')
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# 5. Fourier Transform Analysis"""

# Prepare time series data
fare_series = df_hourly['avg_fare'].values
trip_series = df_hourly['trip_count'].values

# Remove NaN values before FFT
fare_series = np.nan_to_num(fare_series)
trip_series = np.nan_to_num(trip_series)

# Apply FFT
fft_fare = fft.fft(fare_series)
fft_trip = fft.fft(trip_series)

# Get power spectrum
power_fare = np.abs(fft_fare) ** 2
power_trip = np.abs(fft_trip) ** 2

# Get frequencies
freqs = fft.fftfreq(len(fare_series))

# Find dominant frequencies
top_k = 5
top_freq_idx_fare = np.argsort(power_fare)[-top_k:]
top_freq_idx_trip = np.argsort(power_trip)[-top_k:]

print('Top Dominant Frequencies (Fare Price):')
for idx in sorted(top_freq_idx_fare, reverse=True):
    if freqs[idx] > 0:
        period = 1/freqs[idx]
        print(f'  Frequency: {freqs[idx]:.4f}, Period: {period:.1f} hours, Power: {power_fare[idx]:.2e}')

print('\nTop Dominant Frequencies (Trip Count):')
for idx in sorted(top_freq_idx_trip, reverse=True):
    if freqs[idx] > 0:
        period = 1/freqs[idx]
        print(f'  Frequency: {freqs[idx]:.4f}, Period: {period:.1f} hours, Power: {power_trip[idx]:.2e}')

# Plot FFT results
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Only plot positive frequencies
positive_freqs = freqs[:len(freqs)//2]
positive_power_fare = power_fare[:len(power_fare)//2]
positive_power_trip = power_trip[:len(power_trip)//2]

axes[0].semilogy(np.arange(len(positive_freqs)), positive_power_fare)
axes[0].set_xlabel('Frequency Bin')
axes[0].set_ylabel('Power (log scale)')
axes[0].set_title('FFT Power Spectrum - Fare Price')
axes[0].grid(True, alpha=0.3)

axes[1].semilogy(np.arange(len(positive_freqs)), positive_power_trip)
axes[1].set_xlabel('Frequency Bin')
axes[1].set_ylabel('Power (log scale)')
axes[1].set_title('FFT Power Spectrum - Trip Count')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# 6. Clustering Analysis"""

# Tối ưu hóa Clustering Analysis cho 2GB data
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

# === LOCATION CLUSTERING ===
print("=" * 50)
print("LOCATION CLUSTERING")
print("=" * 50)

# Chuẩn hóa dữ liệu trước khi cluster
location_features = df_clean[['pickup_latitude', 'pickup_longitude']].values
scaler_loc = StandardScaler()
location_features_normalized = scaler_loc.fit_transform(location_features)

# Sample để tìm optimal k (5-10% thay vì 10%)
sample_size = min(20000, max(3000, int(len(df_clean) * 0.05)))  # Max 20k, Min 3k
sample_indices = np.random.choice(len(df_clean), size=sample_size, replace=False)
location_features_sample = location_features_normalized[sample_indices]

# Tìm optimal k với range nhỏ hơn
silhouettes = []
K_range = range(3, 8)  # Giảm từ 2-11 xuống 3-7 để tiết kiệm thời gian

for k in K_range:
    # n_init=1 cho MiniBatchKMeans vì nó được thiết kế cho data lớn
    kmeans = MiniBatchKMeans(n_clusters=k, random_state=42, batch_size=1024, n_init=1, max_no_improvement=10)
    kmeans.fit(location_features_sample)
    score = silhouette_score(location_features_sample, kmeans.labels_)
    silhouettes.append(score)
    print(f"K={k}: Silhouette score = {score:.3f}")

# Chọn optimal k
optimal_k = list(K_range)[np.argmax(silhouettes)]
print(f'\n✓ Optimal number of location clusters: {optimal_k}')

# Fit trên FULL data
print(f"Fitting {optimal_k} clusters on {len(df_clean)} samples...")
kmeans_location = MiniBatchKMeans(n_clusters=optimal_k, random_state=42, batch_size=1024, n_init=1)
df_clean['location_cluster'] = kmeans_location.fit_predict(location_features_normalized)

# === TEMPORAL CLUSTERING ===
print("\n" + "=" * 50)
print("TEMPORAL CLUSTERING")
print("=" * 50)

temporal_features = df_clean[['pickup_hour', 'pickup_day_of_week']].values
scaler_temp = StandardScaler()
temporal_features_normalized = scaler_temp.fit_transform(temporal_features)
temporal_features_sample = temporal_features_normalized[sample_indices]

silhouettes_temporal = []
for k in range(3, 8):
    kmeans_temp = MiniBatchKMeans(n_clusters=k, random_state=42, batch_size=1024, n_init=1, max_no_improvement=10)
    kmeans_temp.fit(temporal_features_sample)
    score = silhouette_score(temporal_features_sample, kmeans_temp.labels_)
    silhouettes_temporal.append(score)
    print(f"K={k}: Silhouette score = {score:.3f}")

optimal_k_temporal = list(K_range)[np.argmax(silhouettes_temporal)]
print(f'\n✓ Optimal number of temporal clusters: {optimal_k_temporal}')

# Fit trên FULL data
print(f"Fitting {optimal_k_temporal} clusters on {len(df_clean)} samples...")
kmeans_temporal = MiniBatchKMeans(n_clusters=optimal_k_temporal, random_state=42, batch_size=1024, n_init=1)
df_clean['temporal_cluster'] = kmeans_temporal.fit_predict(temporal_features_normalized)

# Visualize location clusters
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Chuyển cluster centers về coordinates gốc
centers_loc_original = scaler_loc.inverse_transform(kmeans_location.cluster_centers_)

scatter1 = axes[0].scatter(df_clean['pickup_longitude'], df_clean['pickup_latitude'],
                           c=df_clean['location_cluster'], cmap='viridis', alpha=0.5, s=1)
axes[0].scatter(centers_loc_original[:, 1], centers_loc_original[:, 0],
               c='red', s=200, marker='X', edgecolor='black', linewidth=2, label='Centroids')
axes[0].set_xlabel('Longitude')
axes[0].set_ylabel('Latitude')
axes[0].set_title(f'Pickup Location Clusters (K={optimal_k})')
axes[0].legend()
plt.colorbar(scatter1, ax=axes[0])

# Chuyển temporal centers về coordinates gốc
centers_temp_original = scaler_temp.inverse_transform(kmeans_temporal.cluster_centers_)

scatter2 = axes[1].scatter(df_clean['pickup_hour'], df_clean['pickup_day_of_week'],
                           c=df_clean['temporal_cluster'], cmap='plasma', alpha=0.3, s=1)
axes[1].scatter(centers_temp_original[:, 0], centers_temp_original[:, 1],
               c='red', s=200, marker='X', edgecolor='black', linewidth=2, label='Centroids')
axes[1].set_xlabel('Hour of Day')
axes[1].set_ylabel('Day of Week')
axes[1].set_title(f'Temporal Clusters (K={optimal_k_temporal})')
axes[1].set_xticks(range(0, 24, 2))
axes[1].set_yticks(range(0, 7))
axes[1].set_yticklabels(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])
axes[1].legend()
axes[1].grid(True, alpha=0.3)
plt.colorbar(scatter2, ax=axes[1])

plt.tight_layout()
plt.show()

print(f'\nLocation cluster distribution:')
print(df_clean['location_cluster'].value_counts().sort_index())
print(f'\nTemporal cluster distribution:')
print(df_clean['temporal_cluster'].value_counts().sort_index())

"""# 7. Feature Preparation & Scaling"""

# Select features for modeling
feature_cols = [
    'passenger_count', 'trip_distance', 'trip_duration', 'speed',
    'pickup_hour', 'pickup_day', 'pickup_day_of_week', 'is_weekend',
    'hour_sin', 'hour_cos', 'day_sin', 'day_cos',
    'distance_lat', 'distance_lon', 'distance_manhattan',
    'location_cluster', 'temporal_cluster'
]

X = df_clean[feature_cols].fillna(0)
y = df_clean['fare_amount']

# Check for any infinite values
X = X.replace([np.inf, -np.inf], 0)

print(f'Feature matrix shape: {X.shape}')
print(f'Target shape: {y.shape}')
print(f'\nFeature statistics:')
print(X.describe())
print(f'\nTarget statistics:')
print(y.describe())

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f'\nTrain set: {X_train.shape[0]} samples')
print(f'Test set: {X_test.shape[0]} samples')
print(f'Train target - Mean: {y_train.mean():.2f}, Std: {y_train.std():.2f}, Min: {y_train.min():.2f}, Max: {y_train.max():.2f}')

"""# 9. Model Training: Linear Regression (với MLflow Tracking)"""

with mlflow.start_run(run_name="LinearRegression") as run_lr:
    # Log params
    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_param("n_features", len(feature_cols))
    mlflow.log_param("train_size", len(X_train))
    mlflow.log_param("test_size", len(X_test))
    mlflow.log_param("scaler", "StandardScaler")

    # Train
    lr_model = LinearRegression()
    lr_model.fit(X_train_scaled, y_train)

    y_pred_lr_train = lr_model.predict(X_train_scaled)
    y_pred_lr_test  = lr_model.predict(X_test_scaled)

    # Metrics
    lr_train_r2  = r2_score(y_train, y_pred_lr_train)
    lr_test_r2   = r2_score(y_test,  y_pred_lr_test)
    lr_test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr_test))
    lr_test_mae  = mean_absolute_error(y_test, y_pred_lr_test)

    # Log metrics
    mlflow.log_metric("train_r2",  lr_train_r2)
    mlflow.log_metric("test_r2",   lr_test_r2)
    mlflow.log_metric("test_rmse", lr_test_rmse)
    mlflow.log_metric("test_mae",  lr_test_mae)

    # Log model
    signature = infer_signature(X_train_scaled, y_pred_lr_train)
    mlflow.sklearn.log_model(lr_model, artifact_path="model",
                             signature=signature,
                             registered_model_name="LR_NYC_Fare")

    lr_run_id = run_lr.info.run_id

print("Linear Regression Results")
print("=" * 50)
print(f"Run ID: {lr_run_id}")
print(f"Train R²:  {lr_train_r2:.4f}")
print(f"Test  R²:  {lr_test_r2:.4f}")
print(f"Test RMSE: {lr_test_rmse:.4f}")
print(f"Test MAE:  {lr_test_mae:.4f}")
coef_df = pd.DataFrame({"Feature": feature_cols, "Coefficient": lr_model.coef_}).sort_values("Coefficient", key=abs, ascending=False)
print("
Top 10 Feature Coefficients:")
print(coef_df.head(10).to_string(index=False))

"""# 10. Model Training: Random Forest Regressor (với MLflow Tracking)"""

with mlflow.start_run(run_name="RandomForest") as run_rf:
    # Params
    rf_params = dict(n_estimators=100, max_depth=20,
                     min_samples_split=10, min_samples_leaf=5,
                     random_state=42, n_jobs=-1)
    mlflow.log_params(rf_params)
    mlflow.log_param("model_type", "RandomForest")

    # Train
    rf_model = RandomForestRegressor(**rf_params)
    rf_model.fit(X_train, y_train)

    y_pred_rf_train = rf_model.predict(X_train)
    y_pred_rf_test  = rf_model.predict(X_test)

    # Metrics
    rf_train_r2  = r2_score(y_train, y_pred_rf_train)
    rf_test_r2   = r2_score(y_test,  y_pred_rf_test)
    rf_test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf_test))
    rf_test_mae  = mean_absolute_error(y_test, y_pred_rf_test)

    mlflow.log_metric("train_r2",  rf_train_r2)
    mlflow.log_metric("test_r2",   rf_test_r2)
    mlflow.log_metric("test_rmse", rf_test_rmse)
    mlflow.log_metric("test_mae",  rf_test_mae)

    # Log feature importance
    importance_df = pd.DataFrame({"Feature": feature_cols, "Importance": rf_model.feature_importances_}).sort_values("Importance", ascending=False)
    importance_df.to_csv("/tmp/rf_feature_importance.csv", index=False)
    mlflow.log_artifact("/tmp/rf_feature_importance.csv", artifact_path="feature_importance")

    # Log model
    signature = infer_signature(X_train, y_pred_rf_train)
    mlflow.sklearn.log_model(rf_model, artifact_path="model",
                             signature=signature,
                             registered_model_name="RF_NYC_Fare")

    rf_run_id = run_rf.info.run_id

print("Random Forest Results")
print("=" * 50)
print(f"Run ID: {rf_run_id}")
print(f"Train R²:  {rf_train_r2:.4f}")
print(f"Test  R²:  {rf_test_r2:.4f}")
print(f"Test RMSE: {rf_test_rmse:.4f}")
print(f"Test MAE:  {rf_test_mae:.4f}")
print("
Top 10 Feature Importance:")
print(importance_df.head(10).to_string(index=False))

"""# 11. Model Training: XGBoost Regressor (với MLflow Tracking)"""

with mlflow.start_run(run_name="XGBoost") as run_xgb:
    xgb_params = dict(n_estimators=100, max_depth=6, learning_rate=0.1,
                      subsample=0.8, colsample_bytree=0.8,
                      random_state=42, n_jobs=-1, eval_metric="rmse")
    mlflow.log_params(xgb_params)
    mlflow.log_param("model_type", "XGBoost")

    # Train
    xgb_model = xgb.XGBRegressor(**xgb_params)
    xgb_model.fit(X_train, y_train,
                  eval_set=[(X_test, y_test)],
                  verbose=False)

    y_pred_xgb_train = xgb_model.predict(X_train)
    y_pred_xgb_test  = xgb_model.predict(X_test)

    # Metrics
    xgb_train_r2  = r2_score(y_train, y_pred_xgb_train)
    xgb_test_r2   = r2_score(y_test,  y_pred_xgb_test)
    xgb_test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb_test))
    xgb_test_mae  = mean_absolute_error(y_test, y_pred_xgb_test)

    mlflow.log_metric("train_r2",  xgb_train_r2)
    mlflow.log_metric("test_r2",   xgb_test_r2)
    mlflow.log_metric("test_rmse", xgb_test_rmse)
    mlflow.log_metric("test_mae",  xgb_test_mae)

    xgb_importance_df = pd.DataFrame({"Feature": feature_cols, "Importance": xgb_model.feature_importances_}).sort_values("Importance", ascending=False)
    xgb_importance_df.to_csv("/tmp/xgb_feature_importance.csv", index=False)
    mlflow.log_artifact("/tmp/xgb_feature_importance.csv", artifact_path="feature_importance")

    # Log model
    signature = infer_signature(X_train, y_pred_xgb_train)
    mlflow.xgboost.log_model(xgb_model, artifact_path="model",
                              signature=signature,
                              registered_model_name="XGB_NYC_Fare")

    xgb_run_id = run_xgb.info.run_id

print("XGBoost Results")
print("=" * 50)
print(f"Run ID: {xgb_run_id}")
print(f"Train R²:  {xgb_train_r2:.4f}")
print(f"Test  R²:  {xgb_test_r2:.4f}")
print(f"Test RMSE: {xgb_test_rmse:.4f}")
print(f"Test MAE:  {xgb_test_mae:.4f}")
print("
Top 10 Feature Importance:")
print(xgb_importance_df.head(10).to_string(index=False))

"""## MLflow: Best Model & Experiment Summary
So sánh tất cả runs, chọn model tốt nhất và load lại từ registry.
"""

# So sánh tất cả runs trong experiment
import mlflow

experiment = mlflow.get_experiment_by_name("NYC_Taxi_Fare_Prediction")
runs_df = mlflow.search_runs(
    experiment_ids=[experiment.experiment_id],
    order_by=["metrics.test_r2 DESC"]
)

cols_to_show = ["tags.mlflow.runName", "metrics.train_r2", "metrics.test_r2",
                "metrics.test_rmse", "metrics.test_mae", "run_id"]
print("MLflow Experiment Summary")
print("=" * 80)
print(runs_df[cols_to_show].rename(columns=lambda c: c.replace("metrics.","").replace("tags.mlflow.","")).to_string(index=False))

# Chọn best model theo test_r2
best_run = runs_df.iloc[0]
best_model_name = best_run["tags.mlflow.runName"]
best_r2 = best_run["metrics.test_r2"]
best_run_id = best_run["run_id"]

print(f"
🏆 Best Model: {best_model_name}")
print(f"   Test R²:   {best_r2:.4f}")
print(f"   Run ID:    {best_run_id}")

# Load best model từ MLflow
best_model_uri = f"runs:/{best_run_id}/model"
best_model = mlflow.pyfunc.load_model(best_model_uri)
print(f"
✅ Best model loaded từ MLflow: {best_model_uri}")
print("Dùng mlflow ui để xem dashboard!")

"""# 11. Model Comparison & Evaluation"""

# Comparison table
comparison_df = pd.DataFrame({
    'Model': ['Linear Regression', 'Random Forest', 'XGBoost'],
    'Train R²': [lr_train_r2, rf_train_r2, xgb_train_r2],
    'Test R²': [lr_test_r2, rf_test_r2, xgb_test_r2],
    'Test RMSE': [lr_test_rmse, rf_test_rmse, xgb_test_rmse],
    'Test MAE': [lr_test_mae, rf_test_mae, xgb_test_mae]
})

print('\nModel Comparison')
print('=' * 80)
print(comparison_df.to_string(index=False))

print('\n\nBest Models:')
print(f'  Best R²:   {comparison_df.loc[comparison_df["Test R²"].idxmax(), "Model"]} ({comparison_df["Test R²"].max():.4f})')
print(f'  Best RMSE: {comparison_df.loc[comparison_df["Test RMSE"].idxmin(), "Model"]} ({comparison_df["Test RMSE"].min():.4f})')
print(f'  Best MAE:  {comparison_df.loc[comparison_df["Test MAE"].idxmin(), "Model"]} ({comparison_df["Test MAE"].min():.4f})')

"""# 12. Visualizations"""

fig, axes = plt.subplots(2, 3, figsize=(16, 10))

# Prediction scatter plots
axes[0, 0].scatter(y_test, y_pred_lr_test, alpha=0.3, s=1, color='blue')
axes[0, 0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
axes[0, 0].set_xlabel('Actual Fare')
axes[0, 0].set_ylabel('Predicted Fare')
axes[0, 0].set_title(f'Linear Regression (R²={lr_test_r2:.4f})')
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].scatter(y_test, y_pred_rf_test, alpha=0.3, s=1, color='green')
axes[0, 1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
axes[0, 1].set_xlabel('Actual Fare')
axes[0, 1].set_ylabel('Predicted Fare')
axes[0, 1].set_title(f'Random Forest (R²={rf_test_r2:.4f})')
axes[0, 1].grid(True, alpha=0.3)

axes[0, 2].scatter(y_test, y_pred_xgb_test, alpha=0.3, s=1, color='orange')
axes[0, 2].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
axes[0, 2].set_xlabel('Actual Fare')
axes[0, 2].set_ylabel('Predicted Fare')
axes[0, 2].set_title(f'XGBoost (R²={xgb_test_r2:.4f})')
axes[0, 2].grid(True, alpha=0.3)

# Model comparison
x_pos = np.arange(len(comparison_df))
axes[1, 0].bar(x_pos - 0.2, comparison_df['Test RMSE'], 0.4, label='RMSE', alpha=0.8, color='skyblue')
axes[1, 0].bar(x_pos + 0.2, comparison_df['Test MAE'], 0.4, label='MAE', alpha=0.8, color='lightcoral')
axes[1, 0].set_ylabel('Error')
axes[1, 0].set_title('Error Metrics Comparison')
axes[1, 0].set_xticks(x_pos)
axes[1, 0].set_xticklabels(comparison_df['Model'], rotation=15, ha='right')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3, axis='y')

# R² comparison
axes[1, 1].bar(x_pos, comparison_df['Test R²'], alpha=0.8, color=['blue', 'green', 'orange'])
axes[1, 1].set_ylabel('R² Score')
axes[1, 1].set_title('R² Comparison (Test Set)')
axes[1, 1].set_xticks(x_pos)
axes[1, 1].set_xticklabels(comparison_df['Model'], rotation=15, ha='right')
axes[1, 1].set_ylim([0, 1])
axes[1, 1].grid(True, alpha=0.3, axis='y')

# Overfitting check
axes[1, 2].plot(comparison_df['Model'], comparison_df['Train R²'], marker='o', label='Train R²', linewidth=2, markersize=8)
axes[1, 2].plot(comparison_df['Model'], comparison_df['Test R²'], marker='s', label='Test R²', linewidth=2, markersize=8)
axes[1, 2].set_ylabel('R² Score')
axes[1, 2].set_title('Overfitting Analysis')
axes[1, 2].legend()
axes[1, 2].grid(True, alpha=0.3)
plt.setp(axes[1, 2].xaxis.get_majorticklabels(), rotation=15, ha='right')

plt.tight_layout()
plt.show()

"""# 13. Feature Importance Comparison"""

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Random Forest
rf_top = importance_df.head(12)
axes[0].barh(rf_top['Feature'], rf_top['Importance'], color='green', alpha=0.7)
axes[0].set_xlabel('Importance Score')
axes[0].set_title('Random Forest - Top 12 Features')
axes[0].grid(True, alpha=0.3, axis='x')

# XGBoost
xgb_top = xgb_importance_df.head(12)
axes[1].barh(xgb_top['Feature'], xgb_top['Importance'], color='orange', alpha=0.7)
axes[1].set_xlabel('Importance Score')
axes[1].set_title('XGBoost - Top 12 Features')
axes[1].grid(True, alpha=0.3, axis='x')

plt.tight_layout()
plt.show()

"""# 14. Residuals Analysis"""

residuals_lr = y_test - y_pred_lr_test
residuals_rf = y_test - y_pred_rf_test
residuals_xgb = y_test - y_pred_xgb_test

fig, axes = plt.subplots(2, 3, figsize=(16, 8))

# Residuals histograms
axes[0, 0].hist(residuals_lr, bins=50, edgecolor='black', alpha=0.7, color='blue')
axes[0, 0].set_xlabel('Residuals')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].set_title(f'Linear Regression\nMean: {residuals_lr.mean():.4f}, Std: {residuals_lr.std():.4f}')
axes[0, 0].grid(True, alpha=0.3, axis='y')

axes[0, 1].hist(residuals_rf, bins=50, edgecolor='black', alpha=0.7, color='green')
axes[0, 1].set_xlabel('Residuals')
axes[0, 1].set_ylabel('Frequency')
axes[0, 1].set_title(f'Random Forest\nMean: {residuals_rf.mean():.4f}, Std: {residuals_rf.std():.4f}')
axes[0, 1].grid(True, alpha=0.3, axis='y')

axes[0, 2].hist(residuals_xgb, bins=50, edgecolor='black', alpha=0.7, color='orange')
axes[0, 2].set_xlabel('Residuals')
axes[0, 2].set_ylabel('Frequency')
axes[0, 2].set_title(f'XGBoost\nMean: {residuals_xgb.mean():.4f}, Std: {residuals_xgb.std():.4f}')
axes[0, 2].grid(True, alpha=0.3, axis='y')

# Residuals vs predictions
axes[1, 0].scatter(y_pred_lr_test, residuals_lr, alpha=0.3, s=1, color='blue')
axes[1, 0].axhline(y=0, color='r', linestyle='--', lw=2)
axes[1, 0].set_xlabel('Predicted Fare')
axes[1, 0].set_ylabel('Residuals')
axes[1, 0].set_title('Linear Regression Residuals')
axes[1, 0].grid(True, alpha=0.3)

axes[1, 1].scatter(y_pred_rf_test, residuals_rf, alpha=0.3, s=1, color='green')
axes[1, 1].axhline(y=0, color='r', linestyle='--', lw=2)
axes[1, 1].set_xlabel('Predicted Fare')
axes[1, 1].set_ylabel('Residuals')
axes[1, 1].set_title('Random Forest Residuals')
axes[1, 1].grid(True, alpha=0.3)

axes[1, 2].scatter(y_pred_xgb_test, residuals_xgb, alpha=0.3, s=1, color='orange')
axes[1, 2].axhline(y=0, color='r', linestyle='--', lw=2)
axes[1, 2].set_xlabel('Predicted Fare')
axes[1, 2].set_ylabel('Residuals')
axes[1, 2].set_title('XGBoost Residuals')
axes[1, 2].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## Mở MLflow UI trên Kaggle bằng ngrok"""

# Bước 1: Cài ngrok + pyngrok
!pip install pyngrok --quiet

# Bước 2: Điền auth token của bạn từ https://dashboard.ngrok.com/get-started/your-authtoken
NGROK_TOKEN = "34aTl4FSMjLYqD8T12w0nhvXepQ_5xNQkFh5vUA3Eh5tDMQsH"  # <-- thay token vào đây

from pyngrok import ngrok
import subprocess, time

# Bước 3: Thiết lập token
ngrok.set_auth_token(NGROK_TOKEN)

# Bước 4: Khởi động MLflow UI ở background
subprocess.Popen(["mlflow", "ui", "--port", "6000", "--host", "0.0.0.0", "--allowed-hosts"])
time.sleep(3)  # Chờ server khởi động

# Bước 5: Tạo public URL bằng ngrok
public_url = ngrok.connect(5000)
print(f"✅ MLflow UI đang chạy tại: {public_url}")
print("Mở link trên để xem dashboard!")

