apiVersion: v1
kind: ConfigMap
metadata:
  name: nyc-taxi-ingestion-config
  namespace: nyc-taxi
data:
  KAFKA_STARTED_TOPIC: "nyc-taxi-trip-started"
  KAFKA_COMPLETED_TOPIC: "nyc-taxi-trip-completed"
  KAFKA_BOOTSTRAP_SERVERS: "my-kafka-cluster-kafka-bootstrap.ingestion.svc.cluster.local:9092"
  MINIO_ENDPOINT: "http://minio-api.storage.svc.cluster.local:9000"
  RAW_PATH: "s3a://lakehouse/raw/yellow_data"
  BRONZE_STARTED_PATH: "s3a://lakehouse/bronze/nyc-taxi/trip_started"
  BRONZE_COMPLETED_PATH: "s3a://lakehouse/bronze/nyc-taxi/trip_completed"
  SILVER_PATH: "s3a://lakehouse/silver/nyc-taxi/trips"
  STARTED_CHECKPOINT_LOCATION: "s3a://lakehouse/_checkpoints/bronze/trip_started/kafka_to_bronze"
  COMPLETED_CHECKPOINT_LOCATION: "s3a://lakehouse/_checkpoints/bronze/trip_completed/kafka_to_bronze"
