apiVersion: v1
kind: Namespace
metadata:
  name: nyc-taxi
  labels:
    project: nyc-taxi-data-pipeline
    env: development
    tier: application

--- 
apiVersion: v1
kind: Namespace
metadata: 
  name: kafka
  labels:
    project: nyc-taxi-data-pipeline
    env: development
    tier: infrastructure