apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyc-taxi-streaming
  namespace: lakehouse
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nyc-taxi-streaming
  template:
    metadata:
      labels: 
        app: nyc-taxi-streaming
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:latest
          command: 
            - sh
            - -c
            - |
              until nc -z my-kafka-cluster-kafka-bootstrap.ingestion.svc.cluster.local 9092; do
                echo "Waiting for Kafka to be ready..."
                sleep 5
              done
      containers:
        - name: producer
          image: 100.76.120.58:5000/nyc-taxi-replay:v1.0
          imagePullPolicy: Always
          env:
            - name: KAFKA_STARTED_TOPIC
              value: "nyc-taxi-trip-started"
            - name: KAFKA_COMPLETED_TOPIC
              value: "nyc-taxi-trip-completed"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka-cluster-kafka-bootstrap.ingestion.svc.cluster.local:9092"
            - name: DATA_DIR
              value: "/data/yellow_data"
            - name: YEAR
              value: "2025"
            - name: LOOP_STREAMING
              value: "true"
            - name: STREAMING_SPEED_MULTIPLIER
              value: "100"
            - name: STREAMING_BATCH_SIZE
              value: "100"
            - name: STREAMING_MAX_SLEEP_SECONDS
              value: "10"
          resources: 
            requests:
              memory: "1Gi"
              cpu: "256m"
            limits:
              memory: "2Gi"
              cpu: "400m"
          volumeMounts:
            - name: taxi-data
              mountPath: /data
      volumes:
        - name: taxi-data
          persistentVolumeClaim:
            claimName: nfs-nyc-taxi-pvc
