FROM apache/airflow:2.9.3-python3.11

COPY orchestration/airflow/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY orchestration/airflow/dags/ /opt/airflow/dags/
