from pyspark.sql.types import (
    LongType, StructType, StructField,
    StringType, IntegerType, DoubleType, TimestampType
)

BRONZE_COLUMNS = [
    "event_id",
    "event_type",
    "schema_version",
    "source_file",
    "ingest_mode",
    "ingest_timestamp",
    "event_time",
    "trip_date",
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "passenger_count",
    "trip_distance",
    "rate_code_id",
    "store_and_fwd_flag",
    "pulocation_id",
    "dolocation_id",
    "payment_type",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
]

BRONZE_SCHEMA = StructType([
    StructField("event_id", StringType(), False),
    StructField("event_type", StringType(), False),
    StructField("schema_version", StringType(), False),
    StructField("source_file", StringType(), True),
    StructField("ingest_mode", StringType(), False),
    StructField("ingest_timestamp", TimestampType(), False),
    StructField("event_time", TimestampType(), True),
    StructField("trip_date", StringType(), True),
    StructField("vendor_id", IntegerType(), True),
    StructField("pickup_datetime", TimestampType(), True),
    StructField("dropoff_datetime", TimestampType(), True),
    StructField("passenger_count", LongType(), True),
    StructField("trip_distance", DoubleType(), True),
    StructField("rate_code_id", LongType(), True),
    StructField("store_and_fwd_flag", StringType(), True),
    StructField("pulocation_id", IntegerType(), True),
    StructField("dolocation_id", IntegerType(), True),
    StructField("payment_type", IntegerType(), True),
    StructField("fare_amount", DoubleType(), True),
    StructField("extra", DoubleType(), True),
    StructField("mta_tax", DoubleType(), True),
    StructField("tip_amount", DoubleType(), True),
    StructField("tolls_amount", DoubleType(), True),
    StructField("improvement_surcharge", DoubleType(), True),
    StructField("total_amount", DoubleType(), True),
    StructField("congestion_surcharge", DoubleType(), True),
    StructField("airport_fee", DoubleType(), True),
])