apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: nyc-taxi
data:
  KAFKA_TOPIC: "nyc_taxi_events"
  KAFKA_BOOTSTRAP_SERVERS: "my-kafka-cluster-kafka-bootstrap.kafka:9092"
  DATA_DIR: "/data"
  HISTORICAL_FLUSH_EVERY: "3000"
  STREAMING_SPEED_MULTIPLIER: "5.0"
  STREAMING_BATCH_SIZE: "100"
  STREAMING_MAX_SLEEP_SECONDS: "5"
  LOOP_STREAMING: "false"